---

- name: test if functions_strings is set correctly
  assert:
    that:
      - functions_strings is defined
      - functions_strings is iterable
    quiet: yes

- name: test if functions_integers is set correctly
  assert:
    that:
      - functions_integers is defined
      - functions_integers is iterable
    quiet: yes
