---
- name: test if functions_strings is set correctly
  assert:
    that:
      - functions_strings is defined
      - functions_strings | length > 0
      - functions_strings is iterable
    quiet: yes
