---
# tasks file for functions
- name: include assert.yml
  include_tasks: assert.yml

- name: capitalize
  debug:
    msg: "{{ item | capitalize }}"
  loop: "{{ functions_strings }}"

- name: indent
  debug:
    msg: "{{ item | indent }}"
  loop: "{{ functions_strings }}"

- name: list
  debug:
    msg: "{{ item | list }}"
  loop: "{{ functions_strings }}"

- name: lower
  debug:
    msg: "{{ item | lower }}"
  loop: "{{ functions_strings }}"

- name: replace
  debug:
    msg: "{{ item | replace('old', 'new') }}"
  loop: "{{ functions_strings }}"

- name: reverse
  debug:
    msg: "{{ item | reverse }}"
  loop: "{{ functions_strings }}"

- name: string
  debug:
    msg: "{{ item | string }}"
  loop: "{{ functions_strings }}"

- name: trim
  debug:
    msg: "{{ item | trim }}"
  loop: "{{ functions_strings }}"

- name: truncate
  debug:
    msg: "{{ item | truncate(5) }}"
  loop: "{{ functions_strings }}"

- name: upper
  debug:
    msg: "{{ item | upper }}"
  loop: "{{ functions_strings }}"

- name: wordcount
  debug:
    msg: "{{ item | wordcount }}"
  loop: "{{ functions_strings }}"

- name: wordwrap
  debug:
    msg: "{{ item | wordwrap(5) }}"
  loop: "{{ functions_strings }}"

- name: comment
  debug:
    msg: "{{ item | comment }}"
  loop: "{{ functions_strings }}"
